version: '3.9'

services:
    db:
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_DATABASE: creditBoard
            MYSQL_USER: user
            MYSQL_PASSWORD: 12345
            MYSQL_ROOT_PASSWORD: root
        container_name: mydatabase
        ports:
            - "3306:3306"
        volumes:
            - myvolume:/var/lib/mysql

volumes:
    myvolume:

